### ISSUE TITLE
Error compiling hellow world server

### ISSUE THREAD

**Issue by stiv-yakovenko** [tailhook/rotor-http#43]
HI!

I try to compile this file: https://github.com/tailhook/rotor-http/blob/master/examples/hello_world_server.rs

I get this error:

src\main.rs:45:5: 58:6 error: method `headers_received` has an incompatible type for trait:
 expected struct `rotor::scope::Scope`,
    found struct `rotor::Scope` [E0053]
src\main.rs:45     fn headers_received(seed: Self::Seed, head: Head, response: &mut Response,
src\main.rs:46                         scope: &mut ScopeSelf::Context)
src\main.rs:47                         -> Option<(Self, RecvMode, Time)>
src\main.rs:48     {
src\main.rs:49         use self::HelloWorld::*;
src\main.rs:50         scope.increment();

Any ideas why yhis may happen and how to fix it?

**Comment by tailhook** [comment]
Looks like weird dependency versioning problem. Do you use `cargo run --example hello_world_server` in the `rotor-http` dir or do you compile some other way?

**Comment by tailhook** [comment]
If it is, try removing `Cargo.lock` (I had a different error, but it worked, these kind of version updates is a known bug of cargo, BTW).

If it is not, you are probably importing different version of rotor into the project rather than one used to compile rotor-http. You may try to remove `Cargo.lock` as well. Or review/edit it until version of rotor used for rotor-http is the same as version of rotor you import into your project. I mean in `Cargo.toml` they must be compatible, but in `Cargo.lock` they must be same. If versions are compatible in `Cargo.toml` and problem persists, just remove `Cargo.lock` and build again.

**Comment by stiv-yakovenko** [comment]
this is my cargo.toml:

[dependencies]
#hyper = { git = "https://github.com/hyperium/hyper.git" }
rotor-http = { git = "https://github.com/tailhook/rotor-http.git"}
rotor = { git = "https://github.com/tailhook/rotor.git"}

I've removed .lock file, project was rebuild from scratch (deps were refetched, but i still see the same error). Do you want me to share sources?

**Comment by tailhook** [comment]
This is a known issue with git dependencies. You must either use released version. Or use `.cargo/config` to override the version of rotor for rotor-http.

**Comment by stiv-yakovenko** [comment]
@tailhook, please propose what version should I use. Or were can I find version list? Thanx

**Comment by tailhook** [comment]
```
rotor = "0.6.3"
rotor-http = "0.7.0"
```

Just as you see in crates.io

**Comment by stiv-yakovenko** [comment]
Tons of thanx, now it worked!
